### PR TITLE
Use current inbox property

### PR DESCRIPTION
**Pull request by csarven**
As per:
* https://github.com/solid/solid-spec/commit/519e654e47a7ed87b1bc6f02ded56eccb43a4efb#diff-04c6e90faac2675aa89e2176d2eec7d8R239
* https://github.com/solid/node-solid-server/commit/9af2c51a3314ac7435ce8f6558a454304b76411c
* https://github.com/solid/node-solid-server/commit/8b1dc11557416744d2872b49f172bdd208cadf19
* https://github.com/solid/vocab/commit/1cd827c0449f51c9d60920cb86027c3f991a5f7b
* ...

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
👍 looks good to me. Thanks @csarven!

**Comment by RubenVerborgh** [comment]
Hi @melvincarvalho, I think we should move on with this. Using the old property is an error in the documentation that we don't want to propagate.

I've done a grep on the entire repository and @csarven has changed all occurrences. So I will provide a positive review on this PR and merge tomorrow, unless strong objections come up.

**Comment by melvincarvalho** [comment]
@RubenVerborgh @dmitrizagidulin really appreciate your eyes on this, and thank you!

So, there's a couple of subtle points here, which I think think would be helpful go over.

This has been open for ages, isnt hurting anyone, let's discuss in a week or too, if that's OK?

IMHO some really good and exciting developments coming after this week, would just like to put this on hold until after, if that is ok ...

**Comment by melvincarvalho** [comment]
Addendum : please dont let me get in the way of consensus, but have you really evaluated this spec change fully?  Does solid : inbox occur in any of the tests?

IMHO changes to the spec are worth taking a bit of time over!  But, I can live with this change :)

**Comment by melvincarvalho** [comment]
Concretely, please consider that if we want to go this route, the tests should match the proposal, as an example : 

https://github.com/solid/node-solid-server/blob/6f160a5f3000862c6f55d68dcda1aeaa52e4a5b9/test/resources/accounts-acl/config/templates/new-account/profile/card#L21

**Comment by RubenVerborgh** [comment]
So what I'm hearing is that this PR is correct and approved, but that there might be issues in other repositories. So let me merge this and track the rest in #108.

**Comment by melvincarvalho** [comment]
good stuff! FYI : chatted to @RubenVerborgh out of band and went over the background, we've identified some areas to cleanup, which will be covered in other issues

**Pull request merged**
