### PR TITLE
Updated based on some implimentation experience from dokieli

### PR DESCRIPTION
**Pull request by csarven**
Clarified some ideas, based on what works, doesn't, and nice to haves.

### CODE REVIEW

**Comment by rhiaro** [comment]
+1 these look like good improvements

**Comment by melvincarvalho** [comment]
Yes, that looks better.  The property relation here seems pretty important for post processing, tho it appears not (yet) to be in the upstream pingback vocab?

I find the example of friending much more natural than of remote commenting.  Because when you add a relation to your profile, saying that you know someone, you can point someone to that, and additionally ask them to add you back.  

Whearas, generally when you comment on something it will normally be already discoverable in Solid via follow your nose.  I think it would be advantageous in the examples not to train people to scatter data around the web without follow your nose style linking.

Final comment, the term "pingback" is already in use.  The term "ripple" also has a meaning in the web payments group, that is something slightly different, related to cross ledger transactions.  So the choice of codename may become slightly more confusing over time.

**Comment by gobengo** [comment]
cool.

**Comment by csarven** [comment]
@melvincarvalho 

I think that at the moment, we are just piggybacking on (semantic) pingback. We also need to re-consider whether it makes sense to stick around purl.org which we don't have control over at the moment to make any changes, and what's there now is not dereferencing. I prefer to move on. Perhaps this something for https://github.com/solid/vocab to take up. There is nothing specific to Solid, so the vocabulary can rest anywhere.

source, property, target are equally important. They come together, and we should not lose sight over this. There is an exact statement with those three components in the data, and they are used towards the verification. The verification is not about "Something linked to you from somewhere or somehow (without giving further hints), come figure it out based on your implementation and the interpretation of the spec". Does this statement exist? True/False. Do we want it? .. The point is not how much ambiguity can we get away with so that we can write more imperative coding from one implementation to another.

Lets have another example with that you suggest about friending/following a person. I like it.

The claims/pingbacks/interactions/annotations/mentions/notifications/status/activities ... can cover a wide range of stuff. There are some semantic differences between them but high overlap. Different UCs are sufficiently well document. We don't have to have strong favourites, but just aim to describe the core concepts well.

As for scattering data on the Web, we are doing that already, but it doesn't mean that the information is not followed. If for instance I'm on your article, and it provides the interface in which I can start the annotation interaction, and have it saved to my personal space (somewhere else on the Web), and then make sure to inform the article's pingback container about it with that pingback request, this is a good thing. We can follow-our-nose with that. The article may enable the user to do this, but it is also open to agents using their own applications to drop by to leave their claims. As mentioned in the PR title, this works for https://github.com/linkeddata/dokieli .

I'm completely open to the name change. I have some preference to use concepts like 'pingback', '(inter)action', 'activity', 'status', but essentially it is about 'notifying' a claim.

**Comment by rhiaro** [comment]
I think it probably wouldn't hurt to take the terms we need from the pingback vocab to supplement what we already have for solid terms (and add extras like `property`) and put them at a stable w3c namespace.

> I find the example of friending much more natural than of remote commenting. 

Would definitely be good to have different examples of a few different types of interactions.

> Whearas, generally when you comment on something it will normally be already discoverable in Solid via follow your nose. 

The relation would be discoverable from the new comment, but not from the thing commented on unless the former notifies/updates the latter. The whole idea with the pingback mechanism is to enable FYN linking in *both* directions, which is currently missing from solid.

**Pull request merged**
