### PR TITLE
Mark globbing as "at risk"

### PR DESCRIPTION
**Pull request by RubenVerborgh**
As requested by @timbl: point in the spec to the discussion at https://github.com/solid/solid-spec/pull/148 and https://github.com/solid/solid-spec/pull/151.

### CODE REVIEW

**Comment by melvincarvalho** [comment]
Could, at a minimum, specs be versioned, please?

**Comment by RubenVerborgh** [comment]
The point of this is that stakeholders see it, no? We explicitly invite
them to the relevant issues. “At risk” (to me) means: make yourself heard
if you want to keep it.

Other suggestions to attract stakeholders welcome.

**Comment by melvincarvalho** [comment]
> Other suggestions to attract stakeholders welcome.

- identify our apps that use globbing  (eg in our main 2 orgs)
- identify the main authors (e.g. for cimba which was both software and a paper)
- reach out to them with your proposed alternative
- give a time line on which you intend to change status (the last one you gave was 1 day, which should scare the living daylights anyone sane, I hope something more sensible can be proposed)

> “At risk” (to me) means: make yourself heard if you want to keep it.

Had no idea about this, as you have had 4 different views in fewer days, so that's good to know.

**Comment by RubenVerborgh** [comment]
> as you have had 4 different views in fewer days

I fail to see why that was necessary.
I have only one view: globbing must go.

The other PR was to correct errors in the spec you pointed out.
The project I created was to give you a client-side alternative to globbing.
This PR is on request by Tim to others can locate these issues.

**Comment by TallTed** [comment]
@RubenVerborgh @melvincarvalho @kjetilk @michielbdejong (@timbl) - 

I think it important to remember that a publicly posted and available spec in a sphere of "permissionless development," especially a spec developed outside of any spec developing/vetting/blessing organization (so far as I'm aware, the Solid spec did not go through W3, IETF, nor other similar processes), does not offer a good way to reach to all stakeholders who may be impacted by changes to (nor who might offer good be input to the content of) that spec.

That said, this spec does not strike me as nearly the same sort of creature as an IETF RFC or a W3 Rec. Solid server apps and client apps based on this spec are rather fewer than those based on SMTP, NNTP, HTTP, etc., so the number of possible implementation stakeholders is likewise rather smaller.

Also, given that the Solid spec remains in a `0.x` version (the [only version I see is 0.5.0](https://github.com/solid/solid-spec/releases), a version generally understood to indicate _still under development_), it seems to me that *everything* is "at risk", at least until a `1.0` is posted, and that there's a degree of "let the buyer beware" inherent in any implementation based on such a `0.x` spec .

**Comment by elf-pavlik** [comment]
> This PR is on request by Tim so others can locate these issues.

@melvincarvalho as If try to follow globing related threads everyone who currently actively participates in the project seemed to already voiced their opinion. I think everyone had preference to remove that feature, only you seem willing to defend it. I think this gives a ground to mark this feature as 'at risk' and link to related issues, giving this way people who read the spec, possibly wanting to implement it, chance to weigh in.

> *  identify our apps that use globbing (eg in our main 2 orgs)
> *  identify the main authors (e.g. for cimba which was both software and a paper)
> *  reach out to them with your proposed alternative

Since everyone else who expressed their opinion gave :+1: to remove globing, if you care about this feature and would like others to change their stand, you may need to take the steps you suggested yourself. While this PR IMO should land ASAP, #151 can stay pending as long as you want to actively work on changing current rough consensus on removing this feature.

**Comment by solid-pay** [comment]
@melvincarvalho for reasons unexplained is unable to comment further on this issue, or change the state of the review request to approved or dismissed.

But see https://github.com/solid/solid-spec/pull/152#issuecomment-478087931 # posting for a friend ...

**Comment by RubenVerborgh** [comment]
@melvincarvalho My personal unsubscription from your messages seemed to have the unintended consequence of you not being unable to comment, which is unintended and unacceptable. Fixed.

**Comment by melvincarvalho** [comment]
> the unintended consequence of you not being unable to comment, which is unintended and unacceptable

@RubenVerborgh this is not good enough.  Your actions have been disruptive, to me and to the project.  Caused me untold distress and a sleepless night.  I already explained to you that I was sick.

**Comment by RubenVerborgh** [comment]
I had blocked you from my personal account because I do not want any
further interactions with you, as they are not productive for either of us.
I had no way of knowing that this would also ban you from interacting with
others (which I still find a weird GitHub decision). It is now fixed; I
will have to adjust my personal way of working. Please do refrain from
further mentioning me in issues, since I am unable to block you without
unintended consequences.

For the record: no one should ever be banned from our spaces (except for
spammers), especially  not people with your background and experience,
regardless of disagreements. I want you to be able to provide all of your
input; I just no longer wish to react.

**Pull request merged**
